#!/usr/bin/env sh

# Dialog shell script to smoothing wine fonts
# Author: owl4ce
# License: GPL-3.0
# -----------------------------
# https://github.com/owl4ce/wfs

R="\033[1;31m" G="\033[1;32m" M="\033[1;35m" C="\033[1;36m" W="\033[1;37m" NC="\033[0m"

export NEWT_COLORS="
root=,black
shadow=,black
window=,lightgray
border=lightgray,lightgray
textbox=lightgray,gray
listbox=black,lightgray
actlistbox=magenta,lightgray
actsellistbox=red,lightgray
button=green,lightgray"

if ! type "wine" >/dev/null 2>&1; then
    printf "${R}Wine not found!${NC} Is it installed?\n"
    exit 1
fi

if type "whiptail" >/dev/null 2>&1; then
    DIALOG="whiptail"
elif type "dialog" >/dev/null 2>&1; then
    DIALOG="dialog"
else
    printf "${R}Error!${NC} There is no ${M}whiptail${NC} or ${M}dialog${NC} installed.\n"
    exit 1
fi

TMPFILE="$(mktemp)" || exit 1
$DIALOG --menu \
    "                Smoothing Mode" 11 49\
    3\
        1. "ClearType smoothing: RGB (subpixel)"\
        2. "ClearType smoothing: BGR (subpixel)"\
        3. "Disable smoothing" 2> "$TMPFILE"
ANSWER="$(cat $TMPFILE)"

[ "$?" -ne 0 ] && rm -f "$TMPFILE" && exit 1 || :

MODE=0 # 0 = Disabled; 2 = Enabled
TYPE=0 # 1 = Regular;  2 = Subpixel
ORIENTATION=1 # 0 = BGR; 1 = RGB

case $ANSWER in
    1.) MODE=2 # Enable ClearType RGB
        TYPE=2
    ;;
    2.) MODE=2 # Enable ClearType BGR
        TYPE=2
        ORIENTATION=0
    ;;
    3.) # Disabled
    ;;
    *)  rm -f "$TMPFILE"
        printf "${R}Unexpected option:${NC} $ANSWER\n"
        exit 1
    ;;
esac

echo "REGEDIT4
[HKEY_CURRENT_USER\Control Panel\Desktop]
\"FontSmoothing\"=\"$MODE\"
\"FontSmoothingOrientation\"=dword:0000000$ORIENTATION
\"FontSmoothingType\"=dword:0000000$TYPE
\"FontSmoothingGamma\"=dword:00000578" > "$TMPFILE"

printf "\033cApplying changes .. "
$WINE regedit "$TMPFILE" 2> /dev/null
rm -f "$TMPFILE"
printf "${G}OK\n"
